### ISSUE TITLE
value classes for monad transformers?

### ISSUE THREAD

**Issue by ceedubs** [non/cats#546]
Most of Cats' monad transformers (`XorT`, `OptionT`, `StateT`, `Kleisli`, etc) are case classes that simply wrap an underlying structure. Would it be beneficial to use value classes for these structures to potentially avoid object allocations?

For example, if I have an `F[Option[A]]` and a fallback `F[A]`, I'll often use `OptionT(fa).getOrElseF(fallback)` because using the instantly discarded `OptionT` is still more concise than not introducing `OptionT` at all. I think that in this case value classes would allow this approach to not introduce extra allocations.

Are there any downsides to using value classes for this sort of thing?

**Comment by non** [comment]
There's no real downside as far as I know. Any time we talk about the monad transformer instance in a generic context (i.e. `List[OptionT[...]]`) we would end up boxing it, but that's no worse than the status quo now.

:+1:

**Comment by ceedubs** [comment]
I gave this a quick try and our overloading is causing some issues. For example in Kleisli, we have `andThen` which takes a function and `andThen` which takes a `Kleisli`. These two have identical signatures after erasure, so we can't have both. We'll have to rename one or the other. Any naming suggestions? I initially turned the function one to `andThenF`, but we are already using `F` for a different meaning in functions like `flatMapF`, so that seems a bit confusing. Another option that comes to mind is `andThenK` for the `Kleisli` version. I have a slight hesitation there, because it seems like the go-to `andThen` on `Kleisli` itself should be in terms of `Kleisli`.

Anyway, that's a description of my current bikeshedding. I'm hoping someone can offer a good naming suggestion and pull me out of it :)

**Comment by travisbrown** [comment]
There are some bugs to watch out for when working with generic value classes on 2.10—e.g. I've spent half an hour or so banging my head against (what turned out to be) [SI-8018](https://issues.scala-lang.org/browse/SI-8018) on two different occasions.

**Comment by paulp** [comment]
There are still plenty of issues with generic value classes past 2.10, some of which are effectively impossible to fix. For instance.
```scala
package p

class Opt[A](val x: A) extends AnyVal

class Fun[A] extends (Opt[A] => Opt[A]) {
  def apply(x: Opt[A]): Opt[A] = x
}
// a.scala:6: error: bridge generated for member method apply: (x: p.Opt[A])p.Opt[A] in class Fun
// which overrides method apply: (v1: T1)R in trait Function1
// clashes with definition of the member itself;
// both have erased type (v1: Object)Object
//   def apply(x: Opt[A]): Opt[A] = x
//       ^
// one error found
```

**Comment by non** [comment]
I think I am convinced that we should let sleeping dogs (cats) lie in this case and keep things as they are.

**Comment by ceedubs** [comment]
Thanks @travisbrown and @paulp; that's helpful feedback. I now recall that I spent quite a while banging my head against [8011](https://issues.scala-lang.org/browse/SI-8011) as well. I'll close this out.
